[workspace]
members = ["packages/*", "contracts/*"]

[profile.release.package.tg4-group]
codegen-units = 1
incremental = false

[profile.release.package.tg4-mixer]
codegen-units = 1
incremental = false

[profile.release.package.tg4-stake]
codegen-units = 1
incremental = false

[profile.release.package.tgrade-dso]
codegen-units = 1
incremental = false

[profile.release.package.tgrade-gov-reflect]
codegen-units = 1
incremental = false

[profile.release.package.tgrade-valset]
codegen-units = 1
incremental = false


[patch.crates-io]
cw0 = { git = 'https://github.com/CosmWasm/cosmwasm-plus', branch = 'main' }
cw2 = { git = 'https://github.com/CosmWasm/cosmwasm-plus', branch = 'main' }
cw3 = { git = 'https://github.com/CosmWasm/cosmwasm-plus', branch = 'main' }
cw20 = { git = 'https://github.com/CosmWasm/cosmwasm-plus', branch = 'main' }
cw-controllers = { git = 'https://github.com/CosmWasm/cosmwasm-plus', branch = 'main' }
cw-multi-test = { git = 'https://github.com/CosmWasm/cosmwasm-plus', branch = 'main' }
cw-storage-plus = { git = 'https://github.com/CosmWasm/cosmwasm-plus', branch = 'main' }
cosmwasm-std = { git = 'https://github.com/CosmWasm/cosmwasm', version = '0.15.0' }
