[workspace]
members = ["packages/*", "contracts/*"]

[profile.release.package.tg4-engagement]
codegen-units = 1
incremental = false

[profile.release.package.tg4-mixer]
codegen-units = 1
incremental = false

[profile.release.package.tg4-stake]
codegen-units = 1
incremental = false

[profile.release.package.tgrade-dso]
codegen-units = 1
incremental = false

[profile.release.package.tgrade-gov-reflect]
codegen-units = 1
incremental = false

[profile.release.package.tgrade-valset]
codegen-units = 1
incremental = false

[profile.release.package.tgrade-vesting-account]
codegen-units = 1
incremental = false
