[package]
name = "tg-voting-contract"
version = "0.5.0-beta4"
authors = ["Bartłomiej Kuras <bart.k@confio.gmbh>"]
edition = "2018"
description = "Generic utils for building voting contracts for tgrade"
repository = "https://github.com/confio/tgrade-contracts"
homepage = "https://tgrade.finance"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cw0 = "0.10.2"
cw3 = "0.10.2"
cw-storage-plus = "0.10.2"
cosmwasm-std = "1.0.0-beta"
schemars = "0.8.1"
serde = { version = "1", default-features = false, features = ["derive"] }
tg4 = { path = "../tg4", version = "0.5.0-beta4" }
tg-bindings = { path = "../bindings", version = "0.5.0-beta4" }
thiserror = { version = "1" }

