[package]
name = "tgrade-oc-proposals"
version = "v0.5.1"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
description = "Implementing tgrade-oc-proposals"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cw2 = "0.10.2"
cw3 = "0.10.2"
cosmwasm-std = "1.0.0-beta"
schemars = "0.8.1"
serde = { version = "1", default-features = false, features = ["derive"] }
tg4 = { path = "../../packages/tg4", version = "v0.5.1" }
tg4-engagement = { path = "../tg4-engagement", version = "v0.5.1", features = ["library"] }
tg-bindings = { path = "../../packages/bindings", version = "v0.5.1" }
tg-utils = { version = "v0.5.1", path = "../../packages/utils" }
tg-voting-contract = { version = "v0.5.1", path = "../../packages/voting-contract" }
thiserror = "1"
cw-storage-plus = "0.10.2"

[dev-dependencies]
anyhow = "1"
cosmwasm-schema = "1.0.0-beta"
cw-multi-test = "0.10.2"
tg-bindings-test = { version = "v0.5.1", path = "../../packages/bindings-test" }
tg-test-utils = { version = "v0.5.1", path = "../../packages/test-utils" }
tgrade-valset = { path = "../tgrade-valset", version = "v0.5.1", features = ["library"] }
