[package]
name = "tgrade-oc-proposals"
version = "0.8.1"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
description = "Implementing tgrade-oc-proposals"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cw2 = "0.13.2"
cosmwasm-std = "1.0.0-beta8"
schemars = "0.8.1"
serde = { version = "1", default-features = false, features = ["derive"] }
tg3 = "0.8.1"
tg4 = "0.8.1"
tg4-engagement = { version = "0.8.1", features = ["library"] }
tg-bindings = "0.8.1"
tg-utils = "0.8.1"
tg-voting-contract = "0.8.1"
thiserror = "1"
cw-storage-plus = "0.13.2"
tgrade-valset = { version = "0.8.1", features = ["library"] }

[dev-dependencies]
anyhow = "1"
cosmwasm-schema = "1.0.0-beta8"
cw-multi-test = "0.13.2"
tg-bindings-test = "0.8.1"
tg-test-utils = "0.8.1"
