[package]
name = "tgrade-oc-proposals"
version = "0.5.2"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
description = "Implementing tgrade-oc-proposals"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cw2 = "0.11.0"
cw3 = "0.11.0"
cosmwasm-std = "1.0.0-beta"
schemars = "0.8.1"
serde = { version = "1", default-features = false, features = ["derive"] }
tg4 = { git = "ssh://git@github.com/confio/poe-contracts.git", version = "0.5.2" }
tg4-engagement = { git = "ssh://git@github.com/confio/poe-contracts.git", version = "0.5.2" }
tg-bindings = { git = "ssh://git@github.com/confio/poe-contracts.git", version = "0.5.2" }
tg-utils = { git = "ssh://git@github.com/confio/poe-contracts.git", version = "0.5.2" }
tg-voting-contract = { version = "0.5.2", path = "../../packages/voting-contract" }
thiserror = "1"
cw-storage-plus = "0.11.0"

[dev-dependencies]
anyhow = "1"
cosmwasm-schema = "1.0.0-beta"
cw-multi-test = "0.11.0"
tg-bindings-test = { git = "ssh://git@github.com/confio/poe-contracts.git", version = "0.5.2" }
tg-test-utils = { version = "0.5.2", path = "../../packages/test-utils" }
tgrade-valset = { git = "ssh://git@github.com/confio/poe-contracts.git", version = "0.5.2" }
