version: 2
workflows:
  version: 2
  test:
    jobs:
      - contract_tgrade_trusted_circle
      - contract_tgrade_gov_reflect
      - contract_tgrade_oc_proposals
      - contract_tgrade_vesting_account
      - contract_tgrade_ap_voting
  build:
    jobs:
      - lint
      - wasm-build
  deploy:
    jobs:
      - build_and_upload_contracts:
          filters:
           tags:
             only: /^v[0-9]+\.[0-9]+\.[0-9]+.*/
           branches:
             ignore: /.*/
      - build_and_upload_schemas:
          filters:
           tags:
             only: /^v[0-9]+\.[0-9]+\.[0-9]+.*/
           branches:
             ignore: /.*/

jobs:
  contract_tgrade_trusted_circle:
    docker:
      - image: rust:1.53.0
    working_directory: ~/project/contracts/tgrade-trusted-circle
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - restore_cache:
          keys:
            - cargocache-tgrade-trusted-circle-rust:1.53.0-{{ checksum "~/project/Cargo.lock" }}
      - run:
          name: Unit Tests
          environment:
            RUST_BACKTRACE: 1
          command: cargo unit-test --locked
      - run:
          name: Build and run schema generator
          command: cargo schema --locked
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target
          key: cargocache-tgrade-trusted-circle-rust:1.53.0-{{ checksum "~/project/Cargo.lock" }}

  contract_tgrade_gov_reflect:
    docker:
      - image: rust:1.53.0
    working_directory: ~/project/contracts/tgrade-gov-reflect
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - restore_cache:
          keys:
            - cargocache-tgrade-gov-reflect-rust:1.53.0-{{ checksum "~/project/Cargo.lock" }}
      - run:
          name: Unit Tests
          environment:
            RUST_BACKTRACE: 1
          command: cargo unit-test --locked
      - run:
          name: Build and run schema generator
          command: cargo schema --locked
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target
          key: cargocache-tgrade-gov-reflect-rust:1.53.0-{{ checksum "~/project/Cargo.lock" }}

  contract_tgrade_oc_proposals:
    docker:
      - image: rust:1.53.0
    working_directory: ~/project/contracts/tgrade-oc-proposals steps:
      - checkout:
          path: ~/project
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - restore_cache:
          keys:
            - cargocache-tgrade-oc-proposals-rust:1.53.0-{{ checksum "~/project/Cargo.lock" }}
      - run:
          name: Unit Tests
          environment:
            RUST_BACKTRACE: 1
          command: cargo unit-test --locked
      - run:
          name: Build and run schema generator
          command: cargo schema --locked
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target
          key: cargocache-tgrade-oc-proposals-rust:1.53.0-{{ checksum "~/project/Cargo.lock" }}
  contract_tgrade_validator_voting:
    docker:
      - image: rust:1.53.0
    working_directory: ~/project/contracts/tgrade-validator-voting
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - restore_cache:
          keys:
            - cargocache-tgrade-validator-voting-rust:1.53.0-{{ checksum "~/project/Cargo.lock" }}
      - run:
          name: Unit Tests
          environment:
            RUST_BACKTRACE: 1
          command: cargo unit-test --locked
      - run:
          name: Build and run schema generator
          command: cargo schema --locked
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target
          key: cargocache-tgrade-validator-voting-rust:1.53.0-{{ checksum "~/project/Cargo.lock" }}

  contract_tgrade_vesting_account:
    docker:
      - image: rust:1.53.0
    working_directory: ~/project/contracts/tgrade-ap-voting
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - restore_cache:
          keys:
            - cargocache-tgrade-vesting-account-rust:1.53.0-{{ checksum "~/project/Cargo.lock" }}
      - run:
          name: Unit Tests
          environment:
            RUST_BACKTRACE: 1
          command: cargo unit-test --locked
      - run:
          name: Build and run schema generator
          command: cargo schema --locked
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target
          key: cargocache-tgrade-vesting-account-rust:1.53.0-{{ checksum "~/project/Cargo.lock" }}

  contract_tgrade_ap_voting:
    docker:
      - image: rust:1.53.0
    working_directory: ~/project/contracts/tgrade-ap-voting
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - restore_cache:
          keys:
            - cargocache-tgrade-ap-voting-rust:1.53.0-{{ checksum "~/project/Cargo.lock" }}
      - run:
          name: Unit Tests
          environment:
            RUST_BACKTRACE: 1
          command: cargo unit-test --locked
      - run:
          name: Build and run schema generator
          command: cargo schema --locked
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target
          key: cargocache-tgrade-ap-voting-rust:1.53.0-{{ checksum "~/project/Cargo.lock" }}

