[package]
name = "tg-rules-builder"
version = "0.5.0-beta6"
authors = ["Jakub Bogucki <jakub@confio.gmbh>"]
edition = "2018"
description = "Extracted utility to build Rules for voting contracts"
repository = "https://github.com/confio/tgrade-contracts"
homepage = "https://tgrade.finance"

[dependencies]
cosmwasm-std = "1.0.0-beta"
tg-voting-contract = { path = "../voting-contract", version = "0.5.0-beta6" }
