[package]
name = "tg-bindings"
version = "0.4.0"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
description = "Bindings for CustomMsg and CustomQuery for the Tgrade blockchain"
repository = "https://github.com/confio/tgrade-contracts"
homepage = "https://tgrade.finance"

[features]
# multitest is to be enabled in test code to allow using TgradeMsg in multitest
default = []
multitest = ["cw-multi-test", "cw-storage-plus", "anyhow", "thiserror"]

[dependencies]
base64 = "0.13"
cosmwasm-std = { version = "1.0.0-soon" }
schemars = "0.8"
sha2 = "0.9"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

# these are needed only for multitest support
cw-multi-test = { version = "=0.10.0-soon3", optional = true }
cw-storage-plus = { version = "=0.10.0-soon3", optional = true }
anyhow = { version = "1", optional = true }
thiserror = { version = "1.0.21", optional = true }

[dev-dependencies]
cosmwasm-schema = { version = "1.0.0-soon" }
hex-literal = "0.3.1"
