[package]
name = "tg4"
version = "0.1.0"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
description = "Tgrade-4 Interface: Groups Members"
repository = "https://github.com/confio/tgrade-contracts"
homepage = "https://tgrade.finance"

[dependencies]
cosmwasm-std = { version = "0.14.0-beta3" }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

[dev-dependencies]
cosmwasm-schema = { version = "0.14.0-beta3" }
