[package]
name = "tg-utils"
version = "v0.5.1"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
description = "Tgrade Utils: helpers for various contracts"
repository = "https://github.com/confio/tgrade-contracts"
homepage = "https://tgrade.finance"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = "1.0.0-beta"
cw0 = "0.10.2"
cw-controllers = "0.10.2"
cw-storage-plus = "0.10.2"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
tg4 = { path = "../tg4", version = "v0.5.1" }
tg-bindings = { path = "../bindings", version = "v0.5.1" }
thiserror = { version = "1.0.21" }
